**Problem 1:** Create a constant array

In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [5]:
# Create a constant array filled with a specific value (e.g., 7)
constant_array = np.full((2, 2), 7.0)
constant_array

array([[7., 7.],
       [7., 7.]])

---

**Problem 2:** Create an array filled with random values

In [6]:
# Create an array filled with random values (e.g., a 2x2 array of random floats between 0 and 1)
random_array = np.random.rand(2, 2)
print(random_array)

[[0.26662771 0.7936811 ]
 [0.29040993 0.13657534]]


---

**Problem 3:** Create a NumPy array containing the numbers from 10 to 50. Display the array, number of elements, shape, dimension, and data type.

In [8]:
# Create a NumPy array containing numbers from 10 to 50
array_3 = np.arange(10, 51)

# Display the array
print("The array:", array_3)

# Display number of elements
print("Number of elements:", array_3.size)

# Display shape
print("Shape:", array_3.shape)

# Display dimension
print("Dimension:", array_3.ndim)

# Display data type
print("Data type:", array_3.dtype)

The array: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
Number of elements: 41
Shape: (41,)
Dimension: 1
Data type: int64


---

**Problem 4:** Create various NumPy arrays

In [9]:
# Create a 1D array containing 10 zeros
zeros_array = np.zeros(10)
print("1D array of 10 zeros:", zeros_array)

1D array of 10 zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [10]:
# Create a 3x3 array containing ones
ones_array = np.ones((3, 3))
print("\n3x3 array of ones:\n", ones_array)


3x3 array of ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [11]:
# Create a 4x4 identity matrix
identity_matrix = np.eye(4)
print("\n4x4 identity matrix:\n", identity_matrix)


4x4 identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [12]:
# Create an array containing numbers from 5 to 50 with a step size of 5
step_array = np.arange(5, 51, 5)
print("\nArray from 5 to 50 with step 5:", step_array)


Array from 5 to 50 with step 5: [ 5 10 15 20 25 30 35 40 45 50]


---

**Problem 5:** Create an array containing numbers from 1 to 24.

Reshape it into:

*   4 × 6
*   6 × 4
*   2 × 3 × 4

In [13]:
array = np.arange(1, 25)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [14]:
# Reshape to 4x6
array=array.reshape(4, 6)
print(array)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [15]:
# Reshape to 6x4
array=array.reshape(6, 4)
print(array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [16]:
# Reshape to 2x3x4
array=array.reshape(2, 3, 4)
print(array)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


---


**Problem 6:** 

Consider: marks = np.array([78, 85, 92, 67, 88, 73, 95, 81])

Write NumPy statements to display:

*   First element
*   Last element
*   Third element
*   First four elements
*   Last three elements

In [17]:
# Define the marks array
marks = np.array([78, 85, 92, 67, 88, 73, 95, 81])
print(f"Original marks array: {marks}\n")

# Display first element
print(f"First element: {marks[0]}")

# Display last element
print(f"Last element: {marks[-1]}")

# Display third element
print(f"Third element: {marks[2]}")

# Display first four elements
print(f"First four elements: {marks[:4]}")

# Display last three elements
print(f"Last three elements: {marks[-3:]}")

Original marks array: [78 85 92 67 88 73 95 81]

First element: 78
Last element: 81
Third element: 92
First four elements: [78 85 92 67]
Last three elements: [73 95 81]


---

**Problem 7:** Create two NumPy arrays a and b, then calculate a + b, a - b, a * b, a / b, and the square of every element in a.

In [18]:
# Create arrays a and b
a = np.array([10, 20, 30, 40, 50])
b = np.array([5, 10, 15, 20, 25])

print(f"Array a: {a}")
print(f"Array b: {b}\n")

# Calculate a + b
print(f"a + b: {a + b}")

# Calculate a - b
print(f"a - b: {a - b}")

# Calculate a * b
print(f"a * b: {a * b}")

# Calculate a / b
print(f"a / b: {a / b}")

# Calculate square of every element in a
print(f"Square of elements in a: {a**2}")

Array a: [10 20 30 40 50]
Array b: [ 5 10 15 20 25]

a + b: [15 30 45 60 75]
a - b: [ 5 10 15 20 25]
a * b: [  50  200  450  800 1250]
a / b: [2. 2. 2. 2. 2.]
Square of elements in a: [ 100  400  900 1600 2500]


---

**Problem 9:** Given: marks = np.array([45, 78, 89, 32, 67, 90, 55, 76, 41, 84]). Using NumPy boolean indexing.

Find:


*   Marks greater than 75
*   Marks between 50 and 80
*   Number of students who scored below 50
*   Percentage of students who scored 60 or above

Do not use a Python for loop.

In [19]:
marks = np.array([45, 78, 89, 32, 67, 90, 55, 76, 41, 84])
marks

array([45, 78, 89, 32, 67, 90, 55, 76, 41, 84])

In [20]:
# Marks greater than 75
greater_75 = marks[marks > 75]

# Marks between 50 and 80
between_50_80 = marks[(marks >= 50) & (marks <= 80)]

# Number of students below 50
below_50_count = np.sum(marks < 50)

# Percentage of students scoring 60 or above
above_60_count = np.sum(marks >= 60)
percentage_60_or_above = (above_60_count / len(marks)) * 100

print("Marks greater than 75:", greater_75)
print("Marks between 50 and 80:", between_50_80)
print("Students below 50:", below_50_count)
print("Percentage scoring 60 or above:", percentage_60_or_above)

Marks greater than 75: [78 89 90 76 84]
Marks between 50 and 80: [78 67 55 76]
Students below 50: 3
Percentage scoring 60 or above: 60.0


---

**Problem 10:** The following array contains marks of four students in three subjects:

marks = np.array([
    [80, 75, 90],
    [65, 70, 72],
    [88, 92, 85],
    [55, 60, 58]
])

Calculate:


*   Total marks of each student
*   Average marks of each student
*   Average marks in each subject
*   Student with the highest total
*   Highest mark in each subject.

In [21]:
marks = np.array([
    [80, 75, 90],
    [65, 70, 72],
    [88, 92, 85],
    [55, 60, 58]
])

# Total marks of each student
total = np.sum(marks, axis=1)

# Average marks of each student
average = np.mean(marks, axis=1)

# Average marks in each subject
subject_average = np.mean(marks, axis=0)

# Student with highest total
highest_student = np.argmax(total)

# Highest mark in each subject
highest_subject_marks = np.max(marks, axis=0)

print("Total marks:", total)
print("Average marks:", average)
print("Subject averages:", subject_average)
print("Student with highest total:", highest_student + 1)
print("Highest mark in each subject:", highest_subject_marks)

# axis=1 : calculate across columns, so we get the result for each student.
# axis=0 : calculate down rows, so we get the result for each subject.

Total marks: [245 207 265 173]
Average marks: [81.66666667 69.         88.33333333 57.66666667]
Subject averages: [72.   74.25 76.25]
Student with highest total: 3
Highest mark in each subject: [88 92 90]


---

**Problem 11:** Create:

A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

Perform:

*   Matrix addition
*   Element-wise multiplication
*   Matrix multiplication
*   Transpose of A.

explain the difference between:
A * B and A @ B

In [22]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

# Matrix addition
addition = A + B

# Element-wise multiplication
element_multiplication = A * B

# Matrix multiplication
matrix_multiplication = A @ B

# Transpose
transpose_A = A.T

print("Matrix addition:")
print(addition)

print("Element-wise multiplication:")
print(element_multiplication)

print("Matrix multiplication:")
print(matrix_multiplication)

print("Transpose of A:")
print(transpose_A)

Matrix addition:
[[ 6  8]
 [10 12]]
Element-wise multiplication:
[[ 5 12]
 [21 32]]
Matrix multiplication:
[[19 22]
 [43 50]]
Transpose of A:
[[1 3]
 [2 4]]


A * B — Element-wise multiplication

Each corresponding element is multiplied:

1×5   2×6

3×7   4×8

= [[5, 12],
   [21, 32]]

A @ B — Matrix multiplication

Rows of A are multiplied with columns of B:

= [[19, 22],
 [43, 50]]

---

**Problem 12:** Daily temperatures for two weeks are:

temperature = np.array([
    31, 32, 33, 35, 36, 34, 32,
    30, 29, 31, 33, 35, 37, 36
])

Find:

*   Mean temperature
*   Maximum and minimum temperatures
*   Number of days above the average temperature
*   Temperatures greater than 34°C
*   Difference between maximum and minimum
*   Standard deviation

In [23]:
temperature = np.array([
    31, 32, 33, 35, 36, 34, 32,
    30, 29, 31, 33, 35, 37, 36
])

# Mean temperature
mean_temp = np.mean(temperature)
print(f"Mean temperature: {mean_temp:.2f}°C")

# Maximum and minimum temperatures
max_temp = np.max(temperature)
min_temp = np.min(temperature)
print(f"Maximum temperature: {max_temp}°C")
print(f"Minimum temperature: {min_temp}°C")

# Number of days above the average temperature
days_above_average = np.sum(temperature > mean_temp)
print(f"Number of days above average temperature: {days_above_average}")

# Temperatures greater than 34°C
temp_greater_than_34 = temperature[temperature > 34]
print(f"Temperatures greater than 34°C: {temp_greater_than_34}")

# Difference between maximum and minimum
diff_max_min = max_temp - min_temp
print(f"Difference between maximum and minimum: {diff_max_min}°C")

# Standard deviation
std_dev = np.std(temperature)
print(f"Standard deviation: {std_dev:.2f}")

Mean temperature: 33.14°C
Maximum temperature: 37°C
Minimum temperature: 29°C
Number of days above average temperature: 6
Temperatures greater than 34°C: [35 36 35 37 36]
Difference between maximum and minimum: 8°C
Standard deviation: 2.36


---

**Problem 13:** Monthly sales of a company are:
sales = np.array([
    12000, 15000, 17000, 14000,
    18000, 21000, 19000, 22000,
    25000, 23000, 26000, 28000
])

Determine:

*   Total annual sales
*   Average monthly sales
*   Month with the highest sales
*   Month with the lowest sales
*   Number of months with sales above ₹20,000
*   Percentage increase from January to December

Hint: Remember that NumPy indexing starts at 0, while month numbering normally starts at 1.

In [24]:
sales = np.array([
    12000, 15000, 17000, 14000,
    18000, 21000, 19000, 22000,
    25000, 23000, 26000, 28000
])

# Total annual sales
total_sales = np.sum(sales)
print(f"Total annual sales: ₹{total_sales}")

# Average monthly sales
avg_monthly_sales = np.mean(sales)
print(f"Average monthly sales: ₹{avg_monthly_sales:.2f}")

# Month with the highest sales (add 1 because indexing starts from 0)
highest_sales_month_index = np.argmax(sales)
highest_sales_month = highest_sales_month_index + 1
print(f"Month with the highest sales: Month {highest_sales_month} (₹{sales[highest_sales_month_index]})")

# Month with the lowest sales
lowest_sales_month_index = np.argmin(sales)
lowest_sales_month = lowest_sales_month_index + 1
print(f"Month with the lowest sales: Month {lowest_sales_month} (₹{sales[lowest_sales_month_index]})")

# Number of months with sales above ₹20,000
months_above_20k = np.sum(sales > 20000)
print(f"Number of months with sales above ₹20,000: {months_above_20k}")

# Percentage increase from January to December
jan_sales = sales[0]
dec_sales = sales[-1]
percentage_increase = ((dec_sales - jan_sales) / jan_sales) * 100
print(f"Percentage increase from January to December: {percentage_increase:.2f}%")

Total annual sales: ₹240000
Average monthly sales: ₹20000.00
Month with the highest sales: Month 12 (₹28000)
Month with the lowest sales: Month 1 (₹12000)
Number of months with sales above ₹20,000: 6
Percentage increase from January to December: 133.33%


---

**Problem 14:** Consider marks of five students in four subjects:

marks = np.array([
    [78, 85, 90, 88],
    [65, 70, 72, 68],
    [92, 88, 95, 91],
    [55, 60, 58, 62],
    [80, 75, 82, 79]
])

Write a NumPy program that calculates:

*   Total marks of every student
*   Average of every student
*   Average mark for every subject
*   Highest-scoring student
*   Lowest-scoring student
*   Students whose average is greater than 80
*   Overall class average

Then assign a performance category based on average:

|  Average | Category          |
| -------: | ----------------- |
|     ≥ 85 | Excellent         |
| 70–84.99 | Good              |
| 50–69.99 | Average           |
|     < 50 | Needs Improvement |

Challenge: Try assigning these categories using np.where() or np.select() instead of a Python loop.

In [25]:
marks = np.array([
    [78, 85, 90, 88],
    [65, 70, 72, 68],
    [92, 88, 95, 91],
    [55, 60, 58, 62],
    [80, 75, 82, 79]
])

print("Original Marks Array:\n", marks)

# Total marks of every student (sum across columns, axis=1)
total_marks_student = np.sum(marks, axis=1)
print(f"\nTotal marks of each student: {total_marks_student}")

# Average of every student (mean across columns, axis=1)
avg_marks_student = np.mean(marks, axis=1)
print(f"Average marks of each student: {avg_marks_student}")

# Average mark for every subject (mean down rows, axis=0)
avg_marks_subject = np.mean(marks, axis=0)
print(f"Average mark for each subject: {avg_marks_subject}")

# Highest-scoring student (based on total marks)
highest_scoring_student_index = np.argmax(total_marks_student)
print(f"Highest-scoring student: Student {highest_scoring_student_index + 1} (Total: {total_marks_student[highest_scoring_student_index]})")

# Lowest-scoring student (based on total marks)
lowest_scoring_student_index = np.argmin(total_marks_student)
print(f"Lowest-scoring student: Student {lowest_scoring_student_index + 1} (Total: {total_marks_student[lowest_scoring_student_index]})")

# Students whose average is greater than 80
students_avg_above_80 = np.where(avg_marks_student > 80)[0] + 1 # Add 1 for student number
print(f"Students whose average is greater than 80: {students_avg_above_80}")

# Overall class average
overall_class_average = np.mean(marks)
print(f"Overall class average: {overall_class_average:.2f}")

# Assign performance categories using np.select()
conditions = [
    avg_marks_student >= 85,
    (avg_marks_student >= 70) & (avg_marks_student < 85),
    (avg_marks_student >= 50) & (avg_marks_student < 70),
    avg_marks_student < 50
]
choices = ['Excellent', 'Good', 'Average', 'Needs Improvement']

performance_categories = np.select(conditions, choices, default='Unknown')

print("\nPerformance Categories:")
for i, (avg, category) in enumerate(zip(avg_marks_student, performance_categories)):
    print(f"Student {i+1}: Average = {avg:.2f}, Category = {category}")

Original Marks Array:
 [[78 85 90 88]
 [65 70 72 68]
 [92 88 95 91]
 [55 60 58 62]
 [80 75 82 79]]

Total marks of each student: [341 275 366 235 316]
Average marks of each student: [85.25 68.75 91.5  58.75 79.  ]
Average mark for each subject: [74.  75.6 79.4 77.6]
Highest-scoring student: Student 3 (Total: 366)
Lowest-scoring student: Student 4 (Total: 235)
Students whose average is greater than 80: [1 3]
Overall class average: 76.65

Performance Categories:
Student 1: Average = 85.25, Category = Excellent
Student 2: Average = 68.75, Category = Average
Student 3: Average = 91.50, Category = Excellent
Student 4: Average = 58.75, Category = Average
Student 5: Average = 79.00, Category = Good


---

**Problem 15:** Generate 20 random integers between 1 and 100.

In [26]:
random_integers = np.random.randint(1, 101, 20) # 101 because randint is exclusive of the high value
print(f"Generated random integers: {random_integers}")

Generated random integers: [ 7 39 22 13 70 52 90 47 43  9 16 44 14 55 70 23 75 50 16 95]


---

**Problem 16:** Find all even numbers from the generated array (from Problem 15).

In [27]:
even_numbers = random_integers[random_integers % 2 == 0]
print(f"Even numbers: {even_numbers}")

Even numbers: [22 70 52 90 16 44 14 70 50 16]


---

**Problem 17:** Replace values below 50 with 0 (in the array from Problem 15).

In [28]:
modified_array = np.copy(random_integers) # Create a copy to avoid modifying the original
modified_array[modified_array < 50] = 0
print(f"Array with values below 50 replaced by 0: {modified_array}")

Array with values below 50 replaced by 0: [ 0  0  0  0 70 52 90  0  0  0  0  0  0 55 70  0 75 50  0 95]


---

**Problem 18:** Sort the array (from Problem 15) in ascending and descending order.

In [29]:
sorted_ascending = np.sort(random_integers)
print(f"Array sorted in ascending order: {sorted_ascending}")

sorted_descending = np.sort(random_integers)[::-1] # Sort ascending then reverse
print(f"Array sorted in descending order: {sorted_descending}")

Array sorted in ascending order: [ 7  9 13 14 16 16 22 23 39 43 44 47 50 52 55 70 70 75 90 95]
Array sorted in descending order: [95 90 75 70 70 55 52 50 47 44 43 39 23 22 16 16 14 13  9  7]


---

**Problem 19:** Find unique values and their frequencies (in the array from Problem 15).

In [30]:
unique_values, counts = np.unique(random_integers, return_counts=True)
print(f"Unique values: {unique_values}")
print(f"Frequencies: {counts}")

# You can combine them into a dictionary for better readability
frequency_dict = dict(zip(unique_values, counts))
print(f"Unique values and their frequencies (dictionary): {frequency_dict}")

Unique values: [ 7  9 13 14 16 22 23 39 43 44 47 50 52 55 70 75 90 95]
Frequencies: [1 1 1 1 2 1 1 1 1 1 1 1 1 1 2 1 1 1]
Unique values and their frequencies (dictionary): {np.int32(7): np.int64(1), np.int32(9): np.int64(1), np.int32(13): np.int64(1), np.int32(14): np.int64(1), np.int32(16): np.int64(2), np.int32(22): np.int64(1), np.int32(23): np.int64(1), np.int32(39): np.int64(1), np.int32(43): np.int64(1), np.int32(44): np.int64(1), np.int32(47): np.int64(1), np.int32(50): np.int64(1), np.int32(52): np.int64(1), np.int32(55): np.int64(1), np.int32(70): np.int64(2), np.int32(75): np.int64(1), np.int32(90): np.int64(1), np.int32(95): np.int64(1)}


---

**Problem 20:** Create a 5 × 5 random matrix and calculate row-wise and column-wise means.

In [31]:
random_matrix = np.random.rand(5, 5) * 100 # Random floats between 0 and 100
print("Random 5x5 Matrix:\n", random_matrix)

# Row-wise means (mean across columns, axis=1)
row_means = np.mean(random_matrix, axis=1)
print(f"\nRow-wise means: {row_means}")

# Column-wise means (mean down rows, axis=0)
column_means = np.mean(random_matrix, axis=0)
print(f"Column-wise means: {column_means}")

Random 5x5 Matrix:
 [[54.22518561 23.07020578 45.32169646 35.29734851 22.07625737]
 [98.70129126 30.53696452 72.90952298 52.23937623 40.13481349]
 [41.02631084 44.29151718 38.62886987  9.92029913 14.25069272]
 [89.75664567 63.41527198 90.02749683 66.69548667 31.48852533]
 [73.26293407 92.71426648 64.44418098 58.06158894 54.11473209]]

Row-wise means: [35.99813874 58.9043937  29.62353795 68.2766853  68.51954051]
Column-wise means: [71.39447349 50.80564519 62.26635343 44.4428199  32.4130042 ]


---

**Problem 21:** Take your own example to normalize an array (Min-Max Scaling).

In [32]:
data_to_normalize = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print(f"Original array: {data_to_normalize}")

min_val = np.min(data_to_normalize)
max_val = np.max(data_to_normalize)

# Min-Max Normalization: (x - min) / (max - min)
normalized_array = (data_to_normalize - min_val) / (max_val - min_val)
print(f"Normalized array (Min-Max Scaling): {normalized_array}")

Original array: [ 10  20  30  40  50  60  70  80  90 100]
Normalized array (Min-Max Scaling): [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


---

**Problem 22:** Use your own data to standardize an array (Z-score Normalization).

In [33]:
data_to_standardize = np.array([15, 22, 28, 35, 40, 18, 25, 30, 33, 20])
print(f"Original array: {data_to_standardize}")

mean_val = np.mean(data_to_standardize)
std_dev_val = np.std(data_to_standardize)

# Z-score Standardization: (x - mean) / standard_deviation
standardized_array = (data_to_standardize - mean_val) / std_dev_val
print(f"Standardized array (Z-score Normalization): {standardized_array}")

Original array: [15 22 28 35 40 18 25 30 33 20]
Standardized array (Z-score Normalization): [-1.52262967 -0.60380142  0.18376565  1.1025939   1.75889979 -1.12884613
 -0.21001789  0.44628801  0.84007154 -0.86632378]


---

**Problem 23:** Create a NumPy array containing 100 random exam marks and determine how many students fall into the ranges 0–39, 40–59, 60–79, and 80–100.

In [34]:
exam_marks = np.random.randint(0, 101, 100) # 100 random marks between 0 and 100
print(f"Generated 100 exam marks: {exam_marks}\n")

# Count students in each range using boolean indexing
range_0_39 = np.sum((exam_marks >= 0) & (exam_marks <= 39))
range_40_59 = np.sum((exam_marks >= 40) & (exam_marks <= 59))
range_60_79 = np.sum((exam_marks >= 60) & (exam_marks <= 79))
range_80_100 = np.sum((exam_marks >= 80) & (exam_marks <= 100))

print(f"Students in 0-39 range: {range_0_39}")
print(f"Students in 40-59 range: {range_40_59}")
print(f"Students in 60-79 range: {range_60_79}")
print(f"Students in 80-100 range: {range_80_100}")
print(f"Total students counted: {range_0_39 + range_40_59 + range_60_79 + range_80_100}")

Generated 100 exam marks: [61 13 68 42 20 10 81 73 57 70 85 75 96 10 84 42 68 69 15 32 71 71 11 91
 85 73 88 40 25 45 84 33 47 27 85 58 47 97 97  6 75 90 88 87 42 75 17 28
  3 56  5 63 56 53 27 68 66  8 22 67 42 78 12 82 12 49 50 49 33 32 45 55
 80 53 28 83 48  1 87 28 26 90 34 21 73 20 89  7 49  9 94 42 87 41 63 58
 85 27 71 19]

Students in 0-39 range: 33
Students in 40-59 range: 24
Students in 60-79 range: 20
Students in 80-100 range: 23
Total students counted: 100


---

**Problem 24:** Compare the time required to multiply 1,000,000 numbers using a Python list and a NumPy array.

In [35]:
import time

SIZE = 1_000_000 # 1 million numbers

# Python List Multiplication
python_list_a = list(range(SIZE))
python_list_b = list(range(SIZE))

start_time_list = time.time()
result_list = [a * b for a, b in zip(python_list_a, python_list_b)]
end_time_list = time.time()
python_list_time = end_time_list - start_time_list

print(f"Time taken for Python list multiplication: {python_list_time:.6f} seconds")

# NumPy Array Multiplication
numpy_array_a = np.arange(SIZE)
numpy_array_b = np.arange(SIZE)

start_time_numpy = time.time()
result_numpy = numpy_array_a * numpy_array_b
end_time_numpy = time.time()
numpy_array_time = end_time_numpy - start_time_numpy

print(f"Time taken for NumPy array multiplication: {numpy_array_time:.6f} seconds")

print(f"\nNumPy is approximately {python_list_time / numpy_array_time:.2f} times faster than Python lists for this operation.")

Time taken for Python list multiplication: 0.038177 seconds
Time taken for NumPy array multiplication: 0.002000 seconds

NumPy is approximately 19.09 times faster than Python lists for this operation.


---