## **Bias Variance Python Demonstration**

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import make_pipeline
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Generate reproducible non linear data
np.random.seed(42)

#### **Linspace(0,10,40)**

In [2]:
X = np.linspace(0,10,40).reshape(-1,1)

# np.random.normal(0,5,40)is to generate random noise
# and add realistic variation to the output data.
# np.random.normal(mean,standard_deviation, number_of_values)

y = 2 + 0.5 * X[:,0] ** 2 + np.random.normal(0, 5, 40)

# Divide the data
X_train,X_test,y_train,y_test = train_test_split(
    X,y,test_size=0.30,random_state=42
)

degrees=[1,2,10]

# include_bias=False-is to tell PolynominalFeatures not to create
# an additional constant column containing only 1s

for degree in degrees:
    model=make_pipeline(
        PolynomialFeatures(degree=degree,include_bias=False),
        LinearRegression()
    )

    model.fit(X_train, y_train)

    train_pred=model.predict(X_train)
    test_pred=model.predict(X_test)

    train_mse=mean_squared_error(y_train,train_pred)
    test_mse=mean_squared_error(y_test,test_pred)

    print(f"\nPolynomial Degree:{degree}")
    print(f"Training MSE:{train_mse:.2f}")
    print(f"Testing MSE:{test_mse:.2f}")


Polynomial Degree:1
Training MSE:42.90
Testing MSE:42.99

Polynomial Degree:2
Training MSE:20.44
Testing MSE:19.79

Polynomial Degree:10
Training MSE:18.26
Testing MSE:38.42


##### **Degrees=[1,2,3,5,10] & Test_Size = [0.30,0.25,0.20]** 

In [3]:
X_train,X_test,y_train,y_test = train_test_split(
    X,y,test_size=0.30,random_state=42
)

degrees=[1,2,3,5,10]

# include_bias=False-is to tell PolynominalFeatures not to create
# an additional constant column containing only 1s

for degree in degrees:
    model=make_pipeline(
        PolynomialFeatures(degree=degree,include_bias=False),
        LinearRegression()
    )

    model.fit(X_train, y_train)

    train_pred=model.predict(X_train)
    test_pred=model.predict(X_test)

    train_mse=mean_squared_error(y_train,train_pred)
    test_mse=mean_squared_error(y_test,test_pred)

    print(f"\nPolynomial Degree:{degree}")
    print(f"Training MSE:{train_mse:.2f}")
    print(f"Testing MSE:{test_mse:.2f}")


Polynomial Degree:1
Training MSE:42.90
Testing MSE:42.99

Polynomial Degree:2
Training MSE:20.44
Testing MSE:19.79

Polynomial Degree:3
Training MSE:18.46
Testing MSE:22.45

Polynomial Degree:5
Training MSE:17.43
Testing MSE:19.87

Polynomial Degree:10
Training MSE:18.26
Testing MSE:38.42


In [4]:
X_train,X_test,y_train,y_test = train_test_split(
    X,y,test_size=0.25,random_state=42
)

degrees=[1,2,3,5,10]

# include_bias=False-is to tell PolynominalFeatures not to create
# an additional constant column containing only 1s

for degree in degrees:
    model=make_pipeline(
        PolynomialFeatures(degree=degree,include_bias=False),
        LinearRegression()
    )

    model.fit(X_train, y_train)

    train_pred=model.predict(X_train)
    test_pred=model.predict(X_test)

    train_mse=mean_squared_error(y_train,train_pred)
    test_mse=mean_squared_error(y_test,test_pred)

    print(f"\nPolynomial Degree:{degree}")
    print(f"Training MSE:{train_mse:.2f}")
    print(f"Testing MSE:{test_mse:.2f}")


Polynomial Degree:1
Training MSE:40.17
Testing MSE:51.32

Polynomial Degree:2
Training MSE:19.63
Testing MSE:22.09

Polynomial Degree:3
Training MSE:18.05
Testing MSE:23.54

Polynomial Degree:5
Training MSE:16.85
Testing MSE:21.26

Polynomial Degree:10
Training MSE:17.45
Testing MSE:43.67


In [5]:
X_train,X_test,y_train,y_test = train_test_split(
    X,y,test_size=0.20,random_state=42
)

degrees=[1,2,3,5,10]

# include_bias=False-is to tell PolynominalFeatures not to create
# an additional constant column containing only 1s

for degree in degrees:
    model=make_pipeline(
        PolynomialFeatures(degree=degree,include_bias=False),
        LinearRegression()
    )

    model.fit(X_train, y_train)

    train_pred=model.predict(X_train)
    test_pred=model.predict(X_test)

    train_mse=mean_squared_error(y_train,train_pred)
    test_mse=mean_squared_error(y_test,test_pred)

    print(f"\nPolynomial Degree:{degree}")
    print(f"Training MSE:{train_mse:.2f}")
    print(f"Testing MSE:{test_mse:.2f}")


Polynomial Degree:1
Training MSE:44.19
Testing MSE:41.82

Polynomial Degree:2
Training MSE:20.07
Testing MSE:21.48

Polynomial Degree:3
Training MSE:19.41
Testing MSE:19.57

Polynomial Degree:5
Training MSE:17.34
Testing MSE:19.89

Polynomial Degree:10
Training MSE:18.94
Testing MSE:15.78


##### **Comparision**

In [6]:
test_sizes = [0.20, 0.25, 0.30]
degrees = [1, 2, 3, 5, 10]

results = []

for test_size in test_sizes:

    X_train, X_test, y_train, y_test = train_test_split(
        X, y,
        test_size=test_size,
        random_state=42
    )

    for degree in degrees:

        model = make_pipeline(
            PolynomialFeatures(
                degree=degree,
                include_bias=False
            ),
            LinearRegression()
        )

        model.fit(X_train, y_train)

        train_pred = model.predict(X_train)
        test_pred = model.predict(X_test)

        results.append({
            "Test Size": test_size,
            "Degree": degree,
            "Training MSE": mean_squared_error(y_train, train_pred),
            "Testing MSE": mean_squared_error(y_test, test_pred)
        })


results_df = pd.DataFrame(results)

print("Comparison for Dataset 1: X = np.linspace(0, 10, 40)")
print(results_df.round(2).to_string(index=False))


best_models = results_df.loc[
    results_df.groupby("Test Size")["Testing MSE"].idxmin()
]

print("\nBest model for each test size:")
print(best_models.round(2).to_string(index=False))


overall_best = results_df.loc[
    results_df["Testing MSE"].idxmin()
]

print("\nOverall best model for Dataset 1:")
print(overall_best.round(2))

Comparison for Dataset 1: X = np.linspace(0, 10, 40)
 Test Size  Degree  Training MSE  Testing MSE
      0.20       1         44.19        41.82
      0.20       2         20.07        21.48
      0.20       3         19.41        19.57
      0.20       5         17.34        19.89
      0.20      10         18.94        15.78
      0.25       1         40.17        51.32
      0.25       2         19.63        22.09
      0.25       3         18.05        23.54
      0.25       5         16.85        21.26
      0.25      10         17.45        43.67
      0.30       1         42.90        42.99
      0.30       2         20.44        19.79
      0.30       3         18.46        22.45
      0.30       5         17.43        19.87
      0.30      10         18.26        38.42

Best model for each test size:
 Test Size  Degree  Training MSE  Testing MSE
      0.20      10         18.94        15.78
      0.25       5         16.85        21.26
      0.30       2         20.44        1

#### **Linspace(0,500,1000)**

In [7]:
X = np.linspace(0,500,1000).reshape(-1,1)

# np.random.normal(0,5,40)is to generate random noise
# and add realistic variation to the output data.
# np.random.normal(mean,standard_deviation, number_of_values)

y = 2 + 0.5 * X[:,0] ** 2 + np.random.normal(0, 5, 1000)

# Divide the data
X_train,X_test,y_train,y_test = train_test_split(
    X,y,test_size=0.30,random_state=42
)

degrees=[1,2,10]

# include_bias=False-is to tell PolynominalFeatures not to create
# an additional constant column containing only 1s

for degree in degrees:
    model=make_pipeline(
        PolynomialFeatures(degree=degree,include_bias=False),
        LinearRegression()
    )

    model.fit(X_train, y_train)

    train_pred=model.predict(X_train)
    test_pred=model.predict(X_test)

    train_mse=mean_squared_error(y_train,train_pred)
    test_mse=mean_squared_error(y_test,test_pred)

    print(f"\nPolynomial Degree:{degree}")
    print(f"Training MSE:{train_mse:.2f}")
    print(f"Testing MSE:{test_mse:.2f}")


Polynomial Degree:1
Training MSE:84983254.65
Testing MSE:92341929.74

Polynomial Degree:2
Training MSE:23.66
Testing MSE:24.53

Polynomial Degree:10
Training MSE:178276186.34
Testing MSE:182736818.98


##### **Degrees=[1,2,3,5,10] & Test_Size = [0.30,0.25,0.20]** 

In [8]:
X_train,X_test,y_train,y_test = train_test_split(
    X,y,test_size=0.30,random_state=42
)

degrees=[1,2,3,5,10]

# include_bias=False-is to tell PolynominalFeatures not to create
# an additional constant column containing only 1s

for degree in degrees:
    model=make_pipeline(
        PolynomialFeatures(degree=degree,include_bias=False),
        LinearRegression()
    )

    model.fit(X_train, y_train)

    train_pred=model.predict(X_train)
    test_pred=model.predict(X_test)

    train_mse=mean_squared_error(y_train,train_pred)
    test_mse=mean_squared_error(y_test,test_pred)

    print(f"\nPolynomial Degree:{degree}")
    print(f"Training MSE:{train_mse:.2f}")
    print(f"Testing MSE:{test_mse:.2f}")


Polynomial Degree:1
Training MSE:84983254.65
Testing MSE:92341929.74

Polynomial Degree:2
Training MSE:23.66
Testing MSE:24.53

Polynomial Degree:3
Training MSE:23.69
Testing MSE:24.43

Polynomial Degree:5
Training MSE:15981196.49
Testing MSE:16020341.87

Polynomial Degree:10
Training MSE:178276186.34
Testing MSE:182736818.98


In [9]:
X_train,X_test,y_train,y_test = train_test_split(
    X,y,test_size=0.25,random_state=42
)

degrees=[1,2,3,5,10]

# include_bias=False-is to tell PolynominalFeatures not to create
# an additional constant column containing only 1s

for degree in degrees:
    model=make_pipeline(
        PolynomialFeatures(degree=degree,include_bias=False),
        LinearRegression()
    )

    model.fit(X_train, y_train)

    train_pred=model.predict(X_train)
    test_pred=model.predict(X_test)

    train_mse=mean_squared_error(y_train,train_pred)
    test_mse=mean_squared_error(y_test,test_pred)

    print(f"\nPolynomial Degree:{degree}")
    print(f"Training MSE:{train_mse:.2f}")
    print(f"Testing MSE:{test_mse:.2f}")


Polynomial Degree:1
Training MSE:85827437.39
Testing MSE:91205975.71

Polynomial Degree:2
Training MSE:24.09
Testing MSE:23.27

Polynomial Degree:3
Training MSE:24.10
Testing MSE:23.21

Polynomial Degree:5
Training MSE:16030079.97
Testing MSE:15889182.92

Polynomial Degree:10
Training MSE:176550807.12
Testing MSE:188586240.85


In [10]:
X_train,X_test,y_train,y_test = train_test_split(
    X,y,test_size=0.20,random_state=42
)

degrees=[1,2,3,5,10]

# include_bias=False-is to tell PolynominalFeatures not to create
# an additional constant column containing only 1s

for degree in degrees:
    model=make_pipeline(
        PolynomialFeatures(degree=degree,include_bias=False),
        LinearRegression()
    )

    model.fit(X_train, y_train)

    train_pred=model.predict(X_train)
    test_pred=model.predict(X_test)

    train_mse=mean_squared_error(y_train,train_pred)
    test_mse=mean_squared_error(y_test,test_pred)

    print(f"\nPolynomial Degree:{degree}")
    print(f"Training MSE:{train_mse:.2f}")
    print(f"Testing MSE:{test_mse:.2f}")


Polynomial Degree:1
Training MSE:87452332.66
Testing MSE:86134907.07

Polynomial Degree:2
Training MSE:23.79
Testing MSE:24.18

Polynomial Degree:3
Training MSE:23.82
Testing MSE:24.05

Polynomial Degree:5
Training MSE:16182272.82
Testing MSE:15238757.10

Polynomial Degree:10
Training MSE:177805603.95
Testing MSE:186251528.46


##### **Comparision**

In [11]:
test_sizes = [0.20, 0.25, 0.30]
degrees = [1, 2, 3, 5, 10]

results = []

for test_size in test_sizes:

    X_train, X_test, y_train, y_test = train_test_split(
        X, y,
        test_size=test_size,
        random_state=42
    )

    for degree in degrees:

        model = make_pipeline(
            PolynomialFeatures(
                degree=degree,
                include_bias=False
            ),
            LinearRegression()
        )

        model.fit(X_train, y_train)

        train_pred = model.predict(X_train)
        test_pred = model.predict(X_test)

        results.append({
            "Test Size": test_size,
            "Degree": degree,
            "Training MSE": mean_squared_error(y_train, train_pred),
            "Testing MSE": mean_squared_error(y_test, test_pred)
        })


results_df = pd.DataFrame(results)

print("Comparison for Dataset 2: X = np.linspace(0, 500, 1000)")
print(results_df.round(2).to_string(index=False))


best_models = results_df.loc[
    results_df.groupby("Test Size")["Testing MSE"].idxmin()
]

print("\nBest model for each test size:")
print(best_models.round(2).to_string(index=False))


overall_best = results_df.loc[
    results_df["Testing MSE"].idxmin()
]

print("\nOverall best model for Dataset 2:")
print(overall_best.round(2))

Comparison for Dataset 2: X = np.linspace(0, 500, 1000)
 Test Size  Degree  Training MSE  Testing MSE
      0.20       1   87452332.66  86134907.07
      0.20       2         23.79        24.18
      0.20       3         23.82        24.05
      0.20       5   16182272.82  15238757.10
      0.20      10  177805603.95 186251528.46
      0.25       1   85827437.39  91205975.71
      0.25       2         24.09        23.27
      0.25       3         24.10        23.21
      0.25       5   16030079.97  15889182.92
      0.25      10  176550807.12 188586240.85
      0.30       1   84983254.65  92341929.74
      0.30       2         23.66        24.53
      0.30       3         23.69        24.43
      0.30       5   15981196.49  16020341.87
      0.30      10  178276186.34 182736818.98

Best model for each test size:
 Test Size  Degree  Training MSE  Testing MSE
      0.20       3         23.82        24.05
      0.25       3         24.10        23.21
      0.30       3         23.69      

### **Bias Comparision**

##### **Include_bias=False**

In [25]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import make_pipeline
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Generate reproducible non linear data
np.random.seed(42)

X = np.linspace(0,10,40).reshape(-1,1)

# np.random.normal(0,5,40)is to generate random noise
# and add realistic variation to the output data.
# np.random.normal(mean,standard_deviation, number_of_values)

y = 2 + 0.5 * X[:,0] ** 2 + np.random.normal(0, 5, 40)

# Divide the data
X_train,X_test,y_train,y_test = train_test_split(
    X,y,test_size=0.30,random_state=42
)

degrees=[1,2,10]

# include_bias=False-is to tell PolynominalFeatures not to create
# an additional constant column containing only 1s

for degree in degrees:
    model=make_pipeline(
        PolynomialFeatures(degree=degree,include_bias=False),
        LinearRegression()
    )

    model.fit(X_train, y_train)

    train_pred=model.predict(X_train)
    test_pred=model.predict(X_test)

    train_mse=mean_squared_error(y_train,train_pred)
    test_mse=mean_squared_error(y_test,test_pred)

    print(f"\nPolynomial Degree:{degree}")
    print(f"Training MSE:{train_mse:.2f}")
    print(f"Testing MSE:{test_mse:.2f}")

# Check the polynomial features
poly = PolynomialFeatures(degree=2, include_bias=False)

X_transformed = poly.fit_transform(X)
print()
print("\nFeature names:")
print(poly.get_feature_names_out(["X"]))

print("\nFirst five transformed rows:")
print(X_transformed[1:5])


Polynomial Degree:1
Training MSE:42.90
Testing MSE:42.99

Polynomial Degree:2
Training MSE:20.44
Testing MSE:19.79

Polynomial Degree:10
Training MSE:18.26
Testing MSE:38.42


Feature names:
['X' 'X^2']

First five transformed rows:
[[0.25641026 0.06574622]
 [0.51282051 0.26298488]
 [0.76923077 0.59171598]
 [1.02564103 1.05193951]]


##### **Include_bias=True**

In [26]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import make_pipeline
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Generate reproducible non linear data
np.random.seed(42)

X = np.linspace(0,10,40).reshape(-1,1)

# np.random.normal(0,5,40)is to generate random noise
# and add realistic variation to the output data.
# np.random.normal(mean,standard_deviation, number_of_values)

y = 2 + 0.5 * X[:,0] ** 2 + np.random.normal(0, 5, 40)

# Divide the data
X_train,X_test,y_train,y_test = train_test_split(
    X,y,test_size=0.30,random_state=42
)

degrees=[1,2,10]

# include_bias=True -is to tell PolynominalFeatures to create
# an additional constant column containing only 1s

for degree in degrees:
    model=make_pipeline(
        PolynomialFeatures(degree=degree,include_bias=True),
        LinearRegression()
    )
    model.fit(X_train, y_train)

    train_pred=model.predict(X_train)
    test_pred=model.predict(X_test)

    train_mse=mean_squared_error(y_train,train_pred)
    test_mse=mean_squared_error(y_test,test_pred)

    print(f"\nPolynomial Degree:{degree}")
    print(f"Training MSE:{train_mse:.2f}")
    print(f"Testing MSE:{test_mse:.2f}")

# Check the polynomial features
poly = PolynomialFeatures(degree=2, include_bias=True)

X_transformed = poly.fit_transform(X)
print()
print("\nFeature names:")
print(poly.get_feature_names_out(["X"]))

print("\nFirst five transformed rows:")
print(X_transformed[1:5])


Polynomial Degree:1
Training MSE:42.90
Testing MSE:42.99

Polynomial Degree:2
Training MSE:20.44
Testing MSE:19.79

Polynomial Degree:10
Training MSE:18.26
Testing MSE:38.42


Feature names:
['1' 'X' 'X^2']

First five transformed rows:
[[1.         0.25641026 0.06574622]
 [1.         0.51282051 0.26298488]
 [1.         0.76923077 0.59171598]
 [1.         1.02564103 1.05193951]]


##### **Conclusion**


The `include_bias` parameter determines whether `PolynomialFeatures` adds an extra column containing only `1`s.

When `include_bias=False`, the polynomial features contain terms such as:

\[
X,\ X^2,\ X^3,\ldots
\]

When `include_bias=True`, an additional constant term is included:

\[
1,\ X,\ X^2,\ X^3,\ldots
\]

The constant column represents the intercept of the regression equation. However, in this program, `LinearRegression()` uses `fit_intercept=True` by default and already calculates the intercept separately.

Therefore, setting `include_bias=True` adds redundant intercept information. It does not provide any meaningful improvement in the model's performance, and the training MSE and testing MSE should remain almost the same.

Hence, `include_bias=False` is the recommended option in this program because it avoids duplication, keeps the feature matrix simpler, and allows `LinearRegression()` to handle the intercept automatically.